string = "asda asfad asf"
nums = "123 123"
splt = string.split("a")
strp = string.strip()
slcs = string[2:5]
up = string.upper()
low = string.lower()
isup = string()
islow = string.islower()
tittle = string.title()
cap = string.capitalize()
rep = string.replace("a", "op")
isnum = nums.isnumeric()
isdig = nums.isdigit()
find = string.find("a")
words = ["let", "me", "cook"]
j = " ".join(words)